"""add cluster summaries table with versioning

Revision ID: 12b79d268a23
Revises: 0fa290b0f956
Create Date: 2025-09-30 21:44:50.493519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b79d268a23'
down_revision: Union[str, Sequence[str], None] = '0fa290b0f956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_summaries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('summarizer_engine', sa.Text(), server_default='mistral-large-latest', nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=True),
    sa.Column('lang', sa.Text(), server_default='en', nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('bias_analysis_md', sa.Text(), nullable=True),
    sa.Column('timeline_md', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_cluster_summaries_cluster_id_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['cluster_runs.id'], name=op.f('fk_cluster_summaries_run_id_cluster_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_summaries')),
    sa.UniqueConstraint('cluster_id', 'version', name='uq_cluster_summaries_cluster_version')
    )
    op.alter_column('sources', 'kind',
               existing_type=postgresql.ENUM('rss', 'site', 'social', 'api', name='source_kind'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('sources', 'trust_tier',
               existing_type=postgresql.ENUM('A', 'B', 'C', name='source_trust_tier'),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'B'::source_trust_tier"))
    op.alter_column('sources', 'scope',
               existing_type=postgresql.ENUM('local', 'regional', 'national', 'international', name='source_scope'),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'national'::source_scope"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'scope',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('local', 'regional', 'national', 'international', name='source_scope'),
               existing_nullable=False,
               existing_server_default=sa.text("'national'::source_scope"))
    op.alter_column('sources', 'trust_tier',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('A', 'B', 'C', name='source_trust_tier'),
               existing_nullable=False,
               existing_server_default=sa.text("'B'::source_trust_tier"))
    op.alter_column('sources', 'kind',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('rss', 'site', 'social', 'api', name='source_kind'),
               existing_nullable=False)
    op.drop_table('cluster_summaries')
    # ### end Alembic commands ###
