"""add trend metrics and events tables

Revision ID: 9897e6a21d7f
Revises: 12b79d268a23
Create Date: 2025-09-30 23:33:18.287819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9897e6a21d7f'
down_revision: Union[str, Sequence[str], None] = '12b79d268a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('locality', sa.Float(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity in ('low','medium','high','critical')", name=op.f('ck_events_ck_events_severity_valid')),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_events_cluster_id_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['cluster_runs.id'], name=op.f('fk_events_run_id_cluster_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('trend_metrics',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_count', sa.Integer(), nullable=True),
    sa.Column('unique_sources', sa.Integer(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('novelty', sa.Float(), nullable=True),
    sa.Column('locality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_trend_metrics_cluster_id_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['cluster_runs.id'], name=op.f('fk_trend_metrics_run_id_cluster_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ts', 'cluster_id', 'run_id', name=op.f('pk_trend_metrics'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend_metrics')
    op.drop_table('events')
    # ### end Alembic commands ###
