version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  meilisearch:
    image: getmeili/meilisearch:v1.10
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=devMasterKey123
      - MEILI_NO_ANALYTICS=true
    volumes:
      - meili_data:/meili_data

volumes:
  redis_data:
  meili_data:
